export const errorScope = {
  RESOURCE : {
    ALREADY_EXISTS: 101,
    NOT_FOUND: 102,
  },
  AUTHENTICATION: {
    INVALID_CREDENTIALS: 201,
    TOKEN_NOT_FOUND: 202,
    INVALID_TOKEN: 203,
    EXPIRED_TOKEN: 204,
  },
  VALIDATION : 300,
  PERMISSION: 400,
  SERVER_ERROR: 500,
};
